apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: streaming-app
  name: streaming-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: streaming-app
    spec:
      containers:
      - image: streaming-app:latest
        name: streaming-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http-web-svc
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: streaming-app
  name: streaming-app
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: streaming-app
  type: LoadBalancer
status:
  loadBalancer: {}
